# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "Emotion Studios Applications dashboard"
subtitle: ""
logo: ""
icon: "fas fa-cloud-bolt" # Optional icon

header: true
footer: '<p>Created with <span class="has-text-danger">❤️</span> by Wesley</p>' # set false if you want to hide it.

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    background-image: "https://images.unsplash.com/photo-1522679056866-8dbbc8774a9d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2747&q=80"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d600"
    highlight-secondary: "#4285f400"
    backdrop-filter: blur(5px)
    highlight-hover: "#5a95f5"
    background: "#131313"
    background-image: "https://images.unsplash.com/photo-1536125434175-6c5657605fb0?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2370&q=80"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
message:
  #url: https://b4bz.io
  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  title: "Welcome!"
  icon: "fa fa-grin"
  content: "All the services that we create/manage are below. Please contact an administrator for access"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Azure Dev Ops"
    icon: "fab fa-microsoft"
    url: "https://dev.azure.com/e-motionstudios"
    target: "_blank" # optional html a tag target attribute
  - name: "Emotion Studios Documentation Wiki"
    icon: "fas fa-book"
    url: "https://dev.azure.com/e-motionstudios/Emotion%20Studios%20Documentation/_wiki/wikis/Documentation/75/Home"
  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  #- name: "another page!"
  #  icon: "fas fa-file-alt"
  #  url: "#additional-page"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Vantage QA"
    icon: "fas fa-cloud"
    items:
      - name: "Auth Server Portal"
        logo: ""
        subtitle: "GUI to manage user security and Identity Server"
        tag: "angular"
        keywords: ""
        icon: "fas fa-lock"
        url: "https://auth-qa.vantage-sis.co.za"
        target: "_blank" # optional html a tag target attribute
      - name: "Admin Portal"
        logo: ""
        subtitle: "GUI to manage application functionality"
        tag: "angular"
        keywords: ""
        icon: "fas fa-globe"
        url: "https://qa.vantage-sis.co.za"
        target: "_blank" # optional html a tag target attribute
      - name: "Swagger Web Gateway Portal"
        logo: ""
        icon: "fas fa-plug"
        subtitle: "Swagger interface for the API Gateway"
        tag: "web gateway swagger"
        keywords: ""
        url: "https://qa-gateway.vantage-sis.co.za"
        target: "_blank" # optional html a tag target attribute
      - name: "Swagger Web Public Gateway Portal"
        logo: ""
        icon: "fas fa-plug"
        subtitle: "Swagger interface for the Public API Gateway"
        tag: "web gateway swagger"
        keywords: ""
        url: "https://qa-gateway-public.vantage-sis.co.za"
        target: "_blank" # optional html a tag target attribute
  - name: "Vantage Staging"
    icon: "fas fa-cloud"
    items:
      - name: "Auth Server Portal"
        logo: ""
        subtitle: "GUI to manage application functionality"
        tag: "angular"
        keywords: ""
        icon: "fas fa-lock"
        url: "https://auth-staging.vantage-sis.co.za"
        target: "_blank" # optional html a tag target attribute
      - name: "Admin Portal"
        logo: ""
        subtitle: "GUI to manage application functionality"
        tag: "angular"
        keywords: ""
        icon: "fas fa-globe"
        url: "https://staging.vantage-sis.co.za"
        target: "_blank" # optional html a tag target attribute
      - name: "Swagger Web Gateway Portal"
        logo: ""
        icon: "fas fa-plug"
        subtitle: "Swagger interface for the API Gateway"
        tag: "web gateway swagger"
        keywords: ""
        url: "https://staging-gateway.vantage-sis.co.za"
        target: "_blank" # optional html a tag target attribute
      - name: "Swagger Web Public Gateway Portal"
        logo: ""
        icon: "fas fa-plug"
        subtitle: "Swagger interface for the Public API Gateway"
        tag: "web gateway swagger"
        keywords: ""
        url: "https://staging-gateway-public.vantage-sis.co.za"